### ISSUE TITLE
Two optional parameters

### ISSUE THREAD

**Issue by kamalraturi** [atas/lowercase-dashed-route#10]
How to code for two optional parameters by default.

I did this:

 routes.Add(new LowercaseDashedRoute("{controller}/{action}/{catg}/{id}",
      new RouteValueDictionary(
      new { controller = "Accueil", action = "Index", catg = UrlParameter.Optional, id = UrlParameter.Optional }),
      new DashedRouteHandler()
             )
             );

but its not working. It gives url like this:
http://localhost:53197/logiciel/exess/gestion-de-produits-chimiques?catg=fds

It should be like this:
http://localhost:53197/logiciel/exess/fds/gestion-de-produits-chimiques

If used general code(which is commented for LowercaseDashedRoute purpose) then it works fine:
//routes.MapRoute(
            //    name: "Product",
            //    url: "{controller}/{action}/{catg}/{id}",
            //    defaults: new { controller = "Accueil", action = "Index", catg = UrlParameter.Optional, id =      UrlParameter.Optional }
            //);

What am I missing while using LowercaseDashedRoute for two defaults parmeters?

**Comment by salarcode** [comment]
That bug is fixed in my fork.
https://github.com/salarkh/lowercase-dashed-route
https://www.nuget.org/packages/LowercaseDashedRouteExt/

**Comment by kamalraturi** [comment]
Thanks. It works!
