### ISSUE TITLE
.NET 4.0 not supported

### ISSUE THREAD

**Issue by wasphub** [atas/lowercase-dashed-route#2]
Hello

This library is neat and useful, but unluckily "as is" it does not support .NET 4.0, which is still quite widely used. There's nothing special in the library that need .NET 4.5, in fact I took the source code and recompiled it locally under 4.0 and it works like a charm. Would you consider downgrading the required version of .NET to support more scenarios?

Thanks!

**Comment by atas** [comment]
Done. Can you update from nuget, test and confirm it?

**Comment by wasphub** [comment]
Perfect, it works, thanks!

**Comment by atas** [comment]
My pleasure!
