### ISSUE TITLE
Exclude routes

### ISSUE THREAD

**Issue by JimiHFord** [atas/lowercase-dashed-route#3]
First off, thank you so much for this NuGet package! It is extremely helpful. I'm fairly new to MVC so forgive me if this is trivial, but is there anything special I have to do to exclude routes from being transformed into the lowercase route? I'm using a Password Reset Token generated by WebSecurity.GeneratePasswordResetToken(string username, int minutes = 1440) and it is a case sensitive token.

(I added the code straight from your sample code in my route_config)

EDIT:
As it turns out, the case sensitivity is not the problem. The problem is http://localhost:52585/account/resetpassword/p_1kimudjtb-6hq2gzspcq2
becomes
http://localhost:52585/account/reset-password/p_1kimud-jtb-6h-q2gzspc-q2 (due to how the routes are configured to add a dash in between any string that goes from lowercase to uppercase).
The simplest workaround for this is to add
@(new System.UriBuilder(Request.Url.AbsoluteUri) { Path = Url.Action("ResetPassword", "Account", new { id = Model.ConfirmationToken.ToLower() }) }.ToString()) when rendering the absolute URL

This specific issue is solved but a more elegant solution to explicitly excluding routes would be much appreciated :) 

Thank you!

**Comment by atas** [comment]
Hi Jimi,

You can map a route for that url, and you can map it without the lowercase-dashed-routes. Just put its mapping above the lowercase mapping, asp.net mvc matches in order and on the first match it applies matched routing.

More info would be on 
http://www.codeproject.com/Articles/624181/Routing-Basics-in-ASP-NET-MVC
http://www.codeproject.com/Articles/641783/Customizing-Routes-in-ASP-NET-MVC
http://www.asp.net/mvc/tutorials/older-versions/controllers-and-routing/asp-net-mvc-routing-overview-cs

and you can google "asp.net mvc routing" for more. You should really give this some time, it is mandatory to work with asp.net mvc projects and it will save you so much trouble in the future too. Its not that complicated once you understand it.

**Comment by JimiHFord** [comment]
Hi Ata,

Thank you so much!! 10 minutes of reading the first article and I have a much better understanding of it. When I get home from work I will read all of them, I really appreciate your help.

Solution:
routes.MapRoute(
                name: "ResetPassword",
                url: "account/reset-password/{id}",
                defaults: new { controller = "Account", action = "ResetPassword" }
            );
routes.Add(new LowercaseDashedRoute(url: "{controller}/{action}/{id}",
                defaults: new RouteValueDictionary(
                new { controller = "Home", action = "Index", id = UrlParameter.Optional }),
                routeHandler: new DashedRouteHandler()));

Lol wayyy easier than I thought it would be. Thanks!

**Comment by atas** [comment]
Glad to be of help! Now you can create much diverse routes :)
